# Generated by Django 3.1.3 on 2020-11-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(help_text='Format MAJ.MIN.PATCH', max_length=11, primary_key=True, serialize=False, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('key', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='Key')),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patches', to='devlog.version', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Patch',
                'verbose_name_plural': 'Patches',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commit_url', models.URLField(help_text='URL of Commit at Github.', max_length=256, primary_key=True, serialize=False, verbose_name='Commit')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commits', to='devlog.patch', verbose_name='Patch')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commits', to='devlog.version', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'ordering': ('-timestamp',),
            },
        ),
    ]
