# Generated by Django 3.1.3 on 2020-11-16 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('key', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='Key')),
                ('url_arg', models.CharField(db_index=True, editable=False, max_length=100, unique=True, verbose_name='URL Argument')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_active', models.BooleanField(default=True, help_text='This blocks for login.                   The user has no influence on that.', verbose_name='Is Active')),
                ('is_activated_by_key', models.BooleanField(default=False, help_text='This is a user side activation via Email.', verbose_name='Is activated by key')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-registration_date',),
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.SmallIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Key')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('function', models.CharField(choices=[('a', 'Account Activation'), ('pw', 'PW Forgotten')], editable=False, max_length=2, verbose_name='Key Function')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
            },
        ),
    ]
